name: code_diffuser
channels:
  - xformers
  - pytorch3d
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _sysroot_linux-64_curr_repodata_hack=3
  - absl-py=2.1.0
  - accelerate=0.13.2
  - aiohappyeyeballs=2.4.0
  - aiohttp=3.10.5
  - aiosignal=1.3.1
  - antlr-python-runtime=4.9.3
  - aom=3.5.0
  - appdirs=1.4.4
  - arrow-cpp=9.0.0
  - asciitree=0.3.3
  - asttokens=2.4.1
  - async-timeout=4.0.3
  - attrs=24.2.0
  - av=10.0.0
  - aws-c-cal=0.5.11
  - aws-c-common=0.6.2
  - aws-c-event-stream=0.2.7
  - aws-c-io=0.10.5
  - aws-checksums=0.1.11
  - aws-sdk-cpp=1.8.186
  - binutils_impl_linux-64=2.40
  - binutils_linux-64=2.40
  - blas=2.116
  - blas-devel=3.9.0
  - blinker=1.8.2
  - blosc=1.21.5
  - boto3=1.24.96
  - botocore=1.27.96
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.33.1
  - c-blosc2=2.12.0
  - ca-certificates=2024.8.30
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.5.0
  - cairo=1.16.0
  - certifi=2024.8.30
  - cffi=1.15.1
  - cfitsio=4.1.0
  - charls=2.3.4
  - charset-normalizer=3.3.2
  - cloudpickle=3.0.0
  - cmake=3.24.3
  - colorama=0.4.6
  - cryptography=39.0.0
  - cuda-cccl=12.6.37
  - cuda-cccl_linux-64=12.6.37
  - cuda-command-line-tools=12.1.1
  - cuda-compiler=12.6.0
  - cuda-crt-dev_linux-64=12.6.20
  - cuda-crt-tools=12.6.20
  - cuda-cudart=12.1.105
  - cuda-cudart-dev=12.1.105
  - cuda-cudart-dev_linux-64=12.6.68
  - cuda-cudart-static=12.6.68
  - cuda-cudart-static_linux-64=12.6.68
  - cuda-cudart_linux-64=12.6.68
  - cuda-cuobjdump=12.6.68
  - cuda-cupti=12.1.105
  - cuda-cuxxfilt=12.6.68
  - cuda-documentation=12.4.127
  - cuda-driver-dev=12.6.68
  - cuda-driver-dev_linux-64=12.6.68
  - cuda-gdb=12.6.68
  - cuda-libraries=12.1.0
  - cuda-libraries-dev=12.6.0
  - cuda-libraries-static=12.6.1
  - cuda-nsight=12.6.68
  - cuda-nvcc=12.6.20
  - cuda-nvcc-dev_linux-64=12.6.20
  - cuda-nvcc-impl=12.6.20
  - cuda-nvcc-tools=12.6.20
  - cuda-nvcc_linux-64=12.6.20
  - cuda-nvdisasm=12.6.68
  - cuda-nvml-dev=12.6.68
  - cuda-nvprof=12.6.68
  - cuda-nvprune=12.6.68
  - cuda-nvrtc=12.1.105
  - cuda-nvrtc-dev=12.1.105
  - cuda-nvrtc-static=12.6.68
  - cuda-nvtx=12.1.105
  - cuda-nvvm-dev_linux-64=12.6.20
  - cuda-nvvm-impl=12.6.20
  - cuda-nvvm-tools=12.6.20
  - cuda-nvvp=12.6.68
  - cuda-opencl=12.6.68
  - cuda-opencl-dev=12.6.68
  - cuda-profiler-api=12.6.68
  - cuda-runtime=12.1.0
  - cuda-sanitizer-api=12.6.68
  - cuda-toolkit=12.1.0
  - cuda-tools=12.1.1
  - cuda-version=12.6
  - cuda-visual-tools=12.6.0
  - cython=0.29.32
  - cytoolz=0.12.3
  - dask-core=2023.10.1
  - dataclasses=0.8
  - datasets=2.6.1
  - dav1d=1.0.0
  - debugpy=1.8.5
  - decorator=5.1.1
  - diffusers=0.11.1
  - dill=0.3.5.1
  - docker-pycreds=0.4.0
  - einops=0.4.1
  - entrypoints=0.4
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.6.2
  - fasteners=0.17.3
  - ffmpeg=5.1.2
  - filelock=3.15.4
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - fribidi=1.0.10
  - frozenlist=1.4.1
  - fsspec=2024.6.1
  - fvcore=0.1.5.post20221221
  - gcc_impl_linux-64=12.4.0
  - gcc_linux-64=12.4.0
  - gds-tools=1.11.1.6
  - geos=3.11.0
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - gflags=2.2.2
  - giflib=5.2.2
  - gitdb=4.0.11
  - gitpython=3.1.43
  - glog=0.6.0
  - gmp=6.3.0
  - gmpy2=2.1.5
  - gnutls=3.7.9
  - google-auth=2.34.0
  - google-auth-oauthlib=0.4.6
  - graphite2=1.3.13
  - grpc-cpp=1.47.1
  - grpcio=1.47.1
  - gxx_impl_linux-64=12.4.0
  - gxx_linux-64=12.4.0
  - gym=0.21.0
  - h5py=3.7.0
  - harfbuzz=7.3.0
  - hdf5=1.12.2
  - huggingface_hub=0.24.6
  - hydra-core=1.2.0
  - icu=72.1
  - idna=3.8
  - imagecodecs=2022.8.8
  - imageio-ffmpeg=0.4.7
  - importlib-metadata=8.4.0
  - importlib_metadata=8.4.0
  - importlib_resources=6.4.4
  - iopath=0.1.10
  - ipykernel=6.16.2
  - ipython=8.18.1
  - jedi=0.19.1
  - jinja2=3.1.4
  - jmespath=1.0.1
  - jpeg=9e
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - jxrlib=1.1
  - kernel-headers_linux-64=3.10.0
  - keyutils=1.6.1
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.14
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20220623.0
  - libaec=1.1.3
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libass=0.17.1
  - libavif=0.10.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcublas=12.1.0.26
  - libcublas-dev=12.1.0.26
  - libcublas-static=12.6.1.4
  - libcufft=11.0.2.4
  - libcufft-dev=11.0.2.4
  - libcufft-static=11.2.6.59
  - libcufile=1.11.1.6
  - libcufile-dev=1.11.1.6
  - libcufile-static=1.11.1.6
  - libcurand=10.3.7.68
  - libcurand-dev=10.3.7.68
  - libcurand-static=10.3.7.68
  - libcurl=7.87.0
  - libcusolver=11.4.4.55
  - libcusolver-dev=11.4.4.55
  - libcusolver-static=11.6.4.69
  - libcusparse=12.0.2.55
  - libcusparse-dev=12.0.2.55
  - libcusparse-static=12.5.3.3
  - libdeflate=1.14
  - libdrm=2.4.123
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgcc=14.1.0
  - libgcc-devel_linux-64=12.4.0
  - libgcc-ng=14.1.0
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran=14.1.0
  - libgfortran-ng=14.1.0
  - libgfortran5=14.1.0
  - libglib=2.80.3
  - libgomp=14.1.0
  - libgoogle-cloud=2.1.0
  - libhwloc=2.9.3
  - libiconv=1.17
  - libidn2=2.3.7
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm11=11.1.0
  - libnghttp2=1.51.0
  - libnpp=12.0.2.50
  - libnpp-dev=12.0.2.50
  - libnpp-static=12.3.1.54
  - libnsl=2.0.1
  - libnvfatbin=12.6.68
  - libnvfatbin-dev=12.6.68
  - libnvfatbin-static=12.6.68
  - libnvjitlink=12.1.105
  - libnvjitlink-dev=12.1.105
  - libnvjitlink-static=12.6.68
  - libnvjpeg=12.1.1.14
  - libnvjpeg-dev=12.1.1.14
  - libnvjpeg-static=12.3.3.54
  - libnvvm-samples=12.1.105
  - libopus=1.3.1
  - libpciaccess=0.18
  - libpng=1.6.43
  - libprotobuf=3.20.1
  - libsanitizer=12.4.0
  - libsodium=1.0.18
  - libsqlite=3.46.1
  - libssh2=1.10.0
  - libstdcxx=14.1.0
  - libstdcxx-devel_linux-64=12.4.0
  - libstdcxx-ng=14.1.0
  - libtasn1=4.19.0
  - libthrift=0.16.0
  - libtiff=4.4.0
  - libunistring=0.9.10
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libuv=1.48.0
  - libva=2.18.0
  - libvpx=1.13.1
  - libwebp-base=1.4.0
  - libxcb=1.13
  - libxml2=2.11.5
  - libzlib=1.3.1
  - libzopfli=1.0.3
  - llvm-openmp=14.0.6
  - llvmlite=0.39.1
  - locket=1.0.0
  - lz4-c=1.9.4
  - markdown=3.6
  - markupsafe=2.1.5
  - matplotlib-inline=0.1.7
  - mkl=2022.1.0
  - mkl-devel=2022.1.0
  - mkl-include=2022.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - msgpack-python=1.0.8
  - multidict=6.0.5
  - multiprocess=0.70.14
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nettle=3.9.1
  - networkx=3.2.1
  - nsight-compute=2024.1.1.4
  - numba=0.56.4
  - numcodecs=0.10.2
  - oauthlib=3.2.2
  - omegaconf=2.2.3
  - openh264=2.3.1
  - openjpeg=2.5.0
  - openssl=1.1.1w
  - orc=1.7.6
  - p11-kit=0.24.1
  - packaging=24.1
  - pandas=2.2.2
  - parquet-cpp=1.5.1
  - parso=0.8.4
  - partd=1.4.2
  - pathtools=0.1.2
  - pcre2=10.44
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=22.2.2
  - pixman=0.43.2
  - platformdirs=4.2.2
  - portalocker=2.10.1
  - prompt-toolkit=3.0.47
  - protobuf=3.20.1
  - psutil=5.9.2
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyarrow=9.0.0
  - pyasn1=0.6.0
  - pyasn1-modules=0.4.0
  - pycparser=2.22
  - pygments=2.18.0
  - pyjwt=2.9.0
  - pymunk=6.2.1
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - python=3.9.15
  - python-dateutil=2.9.0
  - python-tzdata=2024.1
  - python-xxhash=3.5.0
  - python_abi=3.9
  - pytorch=2.1.0
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pytorch3d=0.7.5
  - pytz=2024.1
  - pyu2f=0.1.5
  - pywavelets=1.6.0
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - re2=2022.06.01
  - readline=8.2
  - regex=2024.7.24
  - requests=2.32.3
  - requests-oauthlib=2.0.0
  - responses=0.18.0
  - rhash=1.4.3
  - rsa=4.9
  - s2n=1.0.10
  - s3transfer=0.6.2
  - scikit-image=0.19.3
  - s